// <auto-generated />
using System;
using CoffeePattisserie.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CoffeePattisserie.Data.Migrations
{
    [DbContext(typeof(CoffeeAppDbContext))]
    [Migration("20240808082702_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.4");

            modelBuilder.Entity("CoffeePattisserie.Entity.Concrete.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsHome")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 8, 8, 11, 27, 1, 866, DateTimeKind.Local).AddTicks(2741),
                            Description = "Various types of coffee",
                            IsActive = true,
                            IsHome = true,
                            ModifiedDate = new DateTime(2024, 8, 8, 11, 27, 1, 866, DateTimeKind.Local).AddTicks(2750),
                            Name = "Coffee"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2024, 8, 8, 11, 27, 1, 866, DateTimeKind.Local).AddTicks(2752),
                            Description = "Various types of moctails",
                            IsActive = true,
                            IsHome = true,
                            ModifiedDate = new DateTime(2024, 8, 8, 11, 27, 1, 866, DateTimeKind.Local).AddTicks(2753),
                            Name = "Moctail"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2024, 8, 8, 11, 27, 1, 866, DateTimeKind.Local).AddTicks(2754),
                            Description = "Various types of pattisseries",
                            IsActive = true,
                            IsHome = true,
                            ModifiedDate = new DateTime(2024, 8, 8, 11, 27, 1, 866, DateTimeKind.Local).AddTicks(2755),
                            Name = "Pattisserie"
                        });
                });

            modelBuilder.Entity("CoffeePattisserie.Entity.Concrete.Coffee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CaffeineContent")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("FlavorNotes")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsHome")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginCountry")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("RoastLevel")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Coffees", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CaffeineContent = 120,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2024, 7, 29, 11, 27, 1, 866, DateTimeKind.Local).AddTicks(7326),
                            FlavorNotes = "Floral, Citrus",
                            ImageUrl = "ethiopian-yirgacheffe.jpg",
                            IsActive = true,
                            IsHome = true,
                            ModifiedDate = new DateTime(2024, 8, 8, 11, 27, 1, 866, DateTimeKind.Local).AddTicks(7325),
                            Name = "Ethiopian Yirgacheffe",
                            OriginCountry = "Ethiopia",
                            Price = 120m,
                            RoastLevel = "Light",
                            StockQuantity = 45
                        },
                        new
                        {
                            Id = 2,
                            CaffeineContent = 110,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2024, 7, 17, 11, 27, 1, 866, DateTimeKind.Local).AddTicks(7336),
                            FlavorNotes = "Nutty, Chocolate",
                            ImageUrl = "colombian-supremo.jpg",
                            IsActive = true,
                            IsHome = false,
                            ModifiedDate = new DateTime(2024, 8, 8, 11, 27, 1, 866, DateTimeKind.Local).AddTicks(7335),
                            Name = "Colombian Supremo",
                            OriginCountry = "Colombia",
                            Price = 125m,
                            RoastLevel = "Medium",
                            StockQuantity = 100
                        },
                        new
                        {
                            Id = 3,
                            CaffeineContent = 100,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2024, 8, 3, 11, 27, 1, 866, DateTimeKind.Local).AddTicks(7340),
                            FlavorNotes = "Earthy, Herbal",
                            ImageUrl = "sumatra-mandheling.jpg",
                            IsActive = true,
                            IsHome = true,
                            ModifiedDate = new DateTime(2024, 8, 8, 11, 27, 1, 866, DateTimeKind.Local).AddTicks(7339),
                            Name = "Sumatra Mandheling",
                            OriginCountry = "Indonesia",
                            Price = 130m,
                            RoastLevel = "Dark",
                            StockQuantity = 30
                        },
                        new
                        {
                            Id = 4,
                            CaffeineContent = 115,
                            CategoryId = 4,
                            CreatedDate = new DateTime(2024, 7, 29, 11, 27, 1, 866, DateTimeKind.Local).AddTicks(7342),
                            FlavorNotes = "Sweet, Nutty",
                            ImageUrl = "brazil-santos.jpg",
                            IsActive = true,
                            IsHome = false,
                            ModifiedDate = new DateTime(2024, 8, 8, 11, 27, 1, 866, DateTimeKind.Local).AddTicks(7342),
                            Name = "Brazil Santos",
                            OriginCountry = "Brazil",
                            Price = 135m,
                            RoastLevel = "Medium",
                            StockQuantity = 120
                        },
                        new
                        {
                            Id = 5,
                            CaffeineContent = 105,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2024, 7, 9, 11, 27, 1, 866, DateTimeKind.Local).AddTicks(7345),
                            FlavorNotes = "Smooth, Sweet, Mild",
                            ImageUrl = "jamaican-blue-mountain.jpg",
                            IsActive = true,
                            IsHome = true,
                            ModifiedDate = new DateTime(2024, 8, 8, 11, 27, 1, 866, DateTimeKind.Local).AddTicks(7344),
                            Name = "Jamaican Blue Mountain",
                            OriginCountry = "Jamaica",
                            Price = 140m,
                            RoastLevel = "Light",
                            StockQuantity = 10
                        },
                        new
                        {
                            Id = 6,
                            CaffeineContent = 110,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2024, 7, 24, 11, 27, 1, 866, DateTimeKind.Local).AddTicks(7348),
                            FlavorNotes = "Fruity, Winey",
                            ImageUrl = "kenyan-aa.jpg",
                            IsActive = true,
                            IsHome = false,
                            ModifiedDate = new DateTime(2024, 8, 8, 11, 27, 1, 866, DateTimeKind.Local).AddTicks(7347),
                            Name = "Kenyan AA",
                            OriginCountry = "Kenya",
                            Price = 145m,
                            RoastLevel = "Medium",
                            StockQuantity = 50
                        },
                        new
                        {
                            Id = 7,
                            CaffeineContent = 115,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2024, 7, 19, 11, 27, 1, 866, DateTimeKind.Local).AddTicks(7350),
                            FlavorNotes = "Citrus, Chocolate",
                            ImageUrl = "costa-rican-tarrazu.jpg",
                            IsActive = true,
                            IsHome = true,
                            ModifiedDate = new DateTime(2024, 8, 8, 11, 27, 1, 866, DateTimeKind.Local).AddTicks(7350),
                            Name = "Costa Rican Tarrazu",
                            OriginCountry = "Costa Rica",
                            Price = 125m,
                            RoastLevel = "Light",
                            StockQuantity = 35
                        },
                        new
                        {
                            Id = 8,
                            CaffeineContent = 105,
                            CategoryId = 4,
                            CreatedDate = new DateTime(2024, 7, 14, 11, 27, 1, 866, DateTimeKind.Local).AddTicks(7353),
                            FlavorNotes = "Spicy, Smoky",
                            ImageUrl = "guatemalan-antigua.jpg",
                            IsActive = true,
                            IsHome = false,
                            ModifiedDate = new DateTime(2024, 8, 8, 11, 27, 1, 866, DateTimeKind.Local).AddTicks(7352),
                            Name = "Guatemalan Antigua",
                            OriginCountry = "Guatemala",
                            Price = 150m,
                            RoastLevel = "Medium",
                            StockQuantity = 20
                        },
                        new
                        {
                            Id = 9,
                            CaffeineContent = 100,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2024, 7, 21, 11, 27, 1, 866, DateTimeKind.Local).AddTicks(7355),
                            FlavorNotes = "Nutty, Caramel",
                            ImageUrl = "mexican-altura.jpg",
                            IsActive = true,
                            IsHome = true,
                            ModifiedDate = new DateTime(2024, 8, 8, 11, 27, 1, 866, DateTimeKind.Local).AddTicks(7355),
                            Name = "Mexican Altura",
                            OriginCountry = "Mexico",
                            Price = 140m,
                            RoastLevel = "Light",
                            StockQuantity = 60
                        },
                        new
                        {
                            Id = 10,
                            CaffeineContent = 110,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2024, 7, 27, 11, 27, 1, 866, DateTimeKind.Local).AddTicks(7358),
                            FlavorNotes = "Rich, Buttery",
                            ImageUrl = "hawaiian-kona.jpg",
                            IsActive = true,
                            IsHome = false,
                            ModifiedDate = new DateTime(2024, 8, 8, 11, 27, 1, 866, DateTimeKind.Local).AddTicks(7358),
                            Name = "Hawaiian Kona",
                            OriginCountry = "Hawaii",
                            Price = 130m,
                            RoastLevel = "Medium",
                            StockQuantity = 15
                        },
                        new
                        {
                            Id = 11,
                            CaffeineContent = 105,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2024, 7, 31, 11, 27, 1, 866, DateTimeKind.Local).AddTicks(7361),
                            FlavorNotes = "Chocolate, Spicy",
                            ImageUrl = "yemen-mocha.jpg",
                            IsActive = true,
                            IsHome = true,
                            ModifiedDate = new DateTime(2024, 8, 8, 11, 27, 1, 866, DateTimeKind.Local).AddTicks(7361),
                            Name = "Yemen Mocha",
                            OriginCountry = "Yemen",
                            Price = 125m,
                            RoastLevel = "Dark",
                            StockQuantity = 25
                        },
                        new
                        {
                            Id = 12,
                            CaffeineContent = 115,
                            CategoryId = 4,
                            CreatedDate = new DateTime(2024, 8, 2, 11, 27, 1, 866, DateTimeKind.Local).AddTicks(7364),
                            FlavorNotes = "Sweet, Floral",
                            ImageUrl = "ecuador-vilcabamba.jpg",
                            IsActive = true,
                            IsHome = false,
                            ModifiedDate = new DateTime(2024, 8, 8, 11, 27, 1, 866, DateTimeKind.Local).AddTicks(7364),
                            Name = "Ecuador Vilcabamba",
                            OriginCountry = "Ecuador",
                            Price = 140m,
                            RoastLevel = "Light",
                            StockQuantity = 20
                        });
                });

            modelBuilder.Entity("CoffeePattisserie.Entity.Concrete.CoffeeCategory", b =>
                {
                    b.Property<int>("CoffeeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.HasKey("CoffeeId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("CoffeeCategories", (string)null);

                    b.HasData(
                        new
                        {
                            CoffeeId = 1,
                            CategoryId = 1
                        },
                        new
                        {
                            CoffeeId = 1,
                            CategoryId = 3
                        },
                        new
                        {
                            CoffeeId = 1,
                            CategoryId = 4
                        },
                        new
                        {
                            CoffeeId = 2,
                            CategoryId = 2
                        },
                        new
                        {
                            CoffeeId = 3,
                            CategoryId = 3
                        },
                        new
                        {
                            CoffeeId = 4,
                            CategoryId = 1
                        },
                        new
                        {
                            CoffeeId = 5,
                            CategoryId = 2
                        },
                        new
                        {
                            CoffeeId = 5,
                            CategoryId = 3
                        },
                        new
                        {
                            CoffeeId = 2,
                            CategoryId = 4
                        },
                        new
                        {
                            CoffeeId = 4,
                            CategoryId = 4
                        },
                        new
                        {
                            CoffeeId = 3,
                            CategoryId = 4
                        },
                        new
                        {
                            CoffeeId = 2,
                            CategoryId = 3
                        },
                        new
                        {
                            CoffeeId = 3,
                            CategoryId = 1
                        });
                });

            modelBuilder.Entity("CoffeePattisserie.Entity.Concrete.Moctail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("FlavorProfile")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Ingredients")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsHome")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PreparationMethod")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Moctails", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2024, 7, 29, 11, 27, 1, 867, DateTimeKind.Local).AddTicks(1142),
                            Description = "A refreshing mint and lime drink.",
                            FlavorProfile = "Minty, Citrusy",
                            ImageUrl = "virgin-mojito.jpg",
                            Ingredients = "Mint, Lime, Soda Water, Sugar",
                            IsActive = true,
                            IsHome = true,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Virgin Mojito",
                            PreparationMethod = "Muddle mint leaves and lime wedges, add sugar and soda water.",
                            Price = 140m,
                            StockQuantity = 50
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2024, 7, 30, 11, 27, 1, 867, DateTimeKind.Local).AddTicks(1150),
                            Description = "A sweet and fizzy drink with grenadine.",
                            FlavorProfile = "Sweet, Fizzy",
                            ImageUrl = "shirley-temple.jpg",
                            Ingredients = "Ginger Ale, Grenadine, Maraschino Cherry",
                            IsActive = true,
                            IsHome = false,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Shirley Temple",
                            PreparationMethod = "Mix ginger ale with grenadine and top with a cherry.",
                            Price = 125m,
                            StockQuantity = 60
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2024, 7, 31, 11, 27, 1, 867, DateTimeKind.Local).AddTicks(1154),
                            Description = "A tropical blend of pineapple and coconut.",
                            FlavorProfile = "Tropical, Creamy",
                            ImageUrl = "pina-colada.jpg",
                            Ingredients = "Pineapple Juice, Coconut Cream, Ice",
                            IsActive = true,
                            IsHome = true,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Pina Colada",
                            PreparationMethod = "Blend pineapple juice and coconut cream with ice.",
                            Price = 150m,
                            StockQuantity = 40
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2024, 8, 1, 11, 27, 1, 867, DateTimeKind.Local).AddTicks(1156),
                            Description = "A fruity drink with orange, pineapple, and lemon.",
                            FlavorProfile = "Fruity, Tangy",
                            ImageUrl = "cinderella.jpg",
                            Ingredients = "Orange Juice, Pineapple Juice, Lemon Juice, Grenadine",
                            IsActive = true,
                            IsHome = false,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Cinderella",
                            PreparationMethod = "Shake all ingredients with ice and strain into a glass.",
                            Price = 130m,
                            StockQuantity = 70
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2024, 8, 2, 11, 27, 1, 867, DateTimeKind.Local).AddTicks(1158),
                            Description = "A vibrant mix of orange and grenadine.",
                            FlavorProfile = "Citrusy, Sweet",
                            ImageUrl = "sunrise.jpg",
                            Ingredients = "Orange Juice, Grenadine, Ice",
                            IsActive = true,
                            IsHome = true,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Sunrise",
                            PreparationMethod = "Pour orange juice over ice and drizzle with grenadine.",
                            Price = 145m,
                            StockQuantity = 55
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2024, 8, 3, 11, 27, 1, 867, DateTimeKind.Local).AddTicks(1161),
                            Description = "A delightful mix of various fruit juices.",
                            FlavorProfile = "Fruity, Refreshing",
                            ImageUrl = "fruit-punch.jpg",
                            Ingredients = "Orange Juice, Pineapple Juice, Cranberry Juice, Lemon Juice",
                            IsActive = true,
                            IsHome = false,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Fruit Punch",
                            PreparationMethod = "Mix all juices together and serve over ice.",
                            Price = 120m,
                            StockQuantity = 65
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2024, 8, 4, 11, 27, 1, 867, DateTimeKind.Local).AddTicks(1163),
                            Description = "A non-alcoholic version of the classic Bloody Mary.",
                            FlavorProfile = "Savory, Spicy",
                            ImageUrl = "virgin-mary.jpg",
                            Ingredients = "Tomato Juice, Lemon Juice, Worcestershire Sauce, Tabasco",
                            IsActive = true,
                            IsHome = true,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Virgin Mary",
                            PreparationMethod = "Mix all ingredients together and serve over ice.",
                            Price = 135m,
                            StockQuantity = 45
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2024, 8, 5, 11, 27, 1, 867, DateTimeKind.Local).AddTicks(1165),
                            Description = "A refreshing mix of various berries.",
                            FlavorProfile = "Berry, Tangy",
                            ImageUrl = "berry-cooler.jpg",
                            Ingredients = "Strawberries, Blueberries, Raspberries, Lemonade",
                            IsActive = true,
                            IsHome = false,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Berry Cooler",
                            PreparationMethod = "Blend all ingredients with ice.",
                            Price = 125m,
                            StockQuantity = 50
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2024, 8, 6, 11, 27, 1, 867, DateTimeKind.Local).AddTicks(1167),
                            Description = "A refreshing lemonade with a hint of mint.",
                            FlavorProfile = "Minty, Citrusy",
                            ImageUrl = "mint-lemonade.jpg",
                            Ingredients = "Lemon Juice, Mint Leaves, Sugar, Water",
                            IsActive = true,
                            IsHome = true,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Mint Lemonade",
                            PreparationMethod = "Mix lemon juice and sugar with water and add mint leaves.",
                            Price = 130m,
                            StockQuantity = 70
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2024, 8, 7, 11, 27, 1, 867, DateTimeKind.Local).AddTicks(1170),
                            Description = "A fizzy drink with tropical flavors.",
                            FlavorProfile = "Tropical, Fizzy",
                            ImageUrl = "tropical-fizz.jpg",
                            Ingredients = "Pineapple Juice, Orange Juice, Soda Water",
                            IsActive = true,
                            IsHome = false,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Tropical Fizz",
                            PreparationMethod = "Mix pineapple juice and orange juice with soda water.",
                            Price = 140m,
                            StockQuantity = 55
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2024, 7, 27, 11, 27, 1, 867, DateTimeKind.Local).AddTicks(1173),
                            Description = "A zesty mix of lemon and ginger ale.",
                            FlavorProfile = "Zesty, Fizzy",
                            ImageUrl = "lemon-ginger-ale.jpg",
                            Ingredients = "Lemon Juice, Ginger Ale, Sugar",
                            IsActive = true,
                            IsHome = false,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Lemon Ginger Ale",
                            PreparationMethod = "Mix lemon juice with ginger ale and add sugar.",
                            Price = 120m,
                            StockQuantity = 60
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2024, 7, 28, 11, 27, 1, 867, DateTimeKind.Local).AddTicks(1175),
                            Description = "A vibrant blue drink with a tropical taste.",
                            FlavorProfile = "Tropical, Sweet",
                            ImageUrl = "blue-lagoon.jpg",
                            Ingredients = "Blue Curacao Syrup, Lemonade, Ice",
                            IsActive = true,
                            IsHome = true,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Blue Lagoon",
                            PreparationMethod = "Mix blue curacao syrup with lemonade and serve over ice.",
                            Price = 145m,
                            StockQuantity = 55
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2024, 7, 29, 11, 27, 1, 867, DateTimeKind.Local).AddTicks(1177),
                            Description = "A refreshing iced tea with a hint of peach.",
                            FlavorProfile = "Peachy, Refreshing",
                            ImageUrl = "peach-iced-tea.jpg",
                            Ingredients = "Peach Syrup, Black Tea, Ice",
                            IsActive = true,
                            IsHome = false,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Peach Iced Tea",
                            PreparationMethod = "Mix peach syrup with black tea and serve over ice.",
                            Price = 135m,
                            StockQuantity = 60
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2024, 7, 30, 11, 27, 1, 867, DateTimeKind.Local).AddTicks(1179),
                            Description = "A tropical twist on the classic Moscow Mule.",
                            FlavorProfile = "Tropical, Spicy",
                            ImageUrl = "mango-mule.jpg",
                            Ingredients = "Mango Juice, Ginger Beer, Lime Juice, Ice",
                            IsActive = true,
                            IsHome = true,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Mango Mule",
                            PreparationMethod = "Mix mango juice and lime juice with ginger beer and serve over ice.",
                            Price = 140m,
                            StockQuantity = 50
                        });
                });

            modelBuilder.Entity("CoffeePattisserie.Entity.Concrete.MoctailCategory", b =>
                {
                    b.Property<int>("MoctailId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.HasKey("MoctailId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("MoctailCategories", (string)null);

                    b.HasData(
                        new
                        {
                            MoctailId = 1,
                            CategoryId = 1
                        },
                        new
                        {
                            MoctailId = 1,
                            CategoryId = 2
                        },
                        new
                        {
                            MoctailId = 2,
                            CategoryId = 3
                        },
                        new
                        {
                            MoctailId = 3,
                            CategoryId = 1
                        },
                        new
                        {
                            MoctailId = 3,
                            CategoryId = 2
                        },
                        new
                        {
                            MoctailId = 4,
                            CategoryId = 4
                        },
                        new
                        {
                            MoctailId = 5,
                            CategoryId = 3
                        },
                        new
                        {
                            MoctailId = 6,
                            CategoryId = 5
                        });
                });

            modelBuilder.Entity("CoffeePattisserie.Entity.Concrete.Pattisserie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Allergens")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Ingredients")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsHome")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ShelfLife")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Pattisseries", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Allergens = "Eggs, Milk, Gluten",
                            CategoryId = 1,
                            CreatedDate = new DateTime(2024, 7, 29, 11, 27, 1, 867, DateTimeKind.Local).AddTicks(4853),
                            Description = "A rich and moist chocolate cake.",
                            ImageUrl = "chocolate-cake.jpg",
                            Ingredients = "Flour, Sugar, Cocoa, Baking Powder, Eggs, Milk",
                            IsActive = true,
                            IsHome = true,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Chocolate Cake",
                            Price = 120m,
                            ShelfLife = "3 days",
                            StockQuantity = 30
                        },
                        new
                        {
                            Id = 2,
                            Allergens = "Eggs, Milk, Gluten",
                            CategoryId = 1,
                            CreatedDate = new DateTime(2024, 7, 30, 11, 27, 1, 867, DateTimeKind.Local).AddTicks(4861),
                            Description = "A fluffy vanilla cupcake with buttercream frosting.",
                            ImageUrl = "vanilla-cupcake.jpg",
                            Ingredients = "Flour, Sugar, Butter, Eggs, Vanilla Extract",
                            IsActive = true,
                            IsHome = false,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Vanilla Cupcake",
                            Price = 125m,
                            ShelfLife = "2 days",
                            StockQuantity = 40
                        },
                        new
                        {
                            Id = 3,
                            Allergens = "Milk, Gluten",
                            CategoryId = 2,
                            CreatedDate = new DateTime(2024, 7, 31, 11, 27, 1, 867, DateTimeKind.Local).AddTicks(4864),
                            Description = "A tart filled with fresh strawberries and cream.",
                            ImageUrl = "strawberry-tart.jpg",
                            Ingredients = "Flour, Sugar, Butter, Strawberries, Cream",
                            IsActive = true,
                            IsHome = true,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Strawberry Tart",
                            Price = 130m,
                            ShelfLife = "1 day",
                            StockQuantity = 25
                        },
                        new
                        {
                            Id = 4,
                            Allergens = "Eggs, Milk, Gluten",
                            CategoryId = 2,
                            CreatedDate = new DateTime(2024, 8, 1, 11, 27, 1, 867, DateTimeKind.Local).AddTicks(4867),
                            Description = "A tart lemon pie with a fluffy meringue topping.",
                            ImageUrl = "lemon-meringue-pie.jpg",
                            Ingredients = "Flour, Sugar, Eggs, Lemons, Butter",
                            IsActive = true,
                            IsHome = false,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Lemon Meringue Pie",
                            Price = 145m,
                            ShelfLife = "2 days",
                            StockQuantity = 20
                        },
                        new
                        {
                            Id = 5,
                            Allergens = "Eggs, Milk, Gluten",
                            CategoryId = 3,
                            CreatedDate = new DateTime(2024, 8, 2, 11, 27, 1, 867, DateTimeKind.Local).AddTicks(4869),
                            Description = "A moist muffin packed with fresh blueberries.",
                            ImageUrl = "blueberry-muffin.jpg",
                            Ingredients = "Flour, Sugar, Blueberries, Eggs, Milk",
                            IsActive = true,
                            IsHome = true,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Blueberry Muffin",
                            Price = 135m,
                            ShelfLife = "3 days",
                            StockQuantity = 35
                        },
                        new
                        {
                            Id = 6,
                            Allergens = "Eggs, Milk, Gluten",
                            CategoryId = 3,
                            CreatedDate = new DateTime(2024, 8, 3, 11, 27, 1, 867, DateTimeKind.Local).AddTicks(4871),
                            Description = "A creamy cheesecake with a raspberry swirl.",
                            ImageUrl = "raspberry-cheesecake.jpg",
                            Ingredients = "Cream Cheese, Sugar, Eggs, Raspberries, Graham Cracker Crust",
                            IsActive = true,
                            IsHome = false,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Raspberry Cheesecake",
                            Price = 140m,
                            ShelfLife = "5 days",
                            StockQuantity = 15
                        },
                        new
                        {
                            Id = 7,
                            Allergens = "Eggs, Milk, Gluten",
                            CategoryId = 1,
                            CreatedDate = new DateTime(2024, 8, 4, 11, 27, 1, 867, DateTimeKind.Local).AddTicks(4873),
                            Description = "A classic cookie loaded with chocolate chips.",
                            ImageUrl = "chocolate-chip-cookie.jpg",
                            Ingredients = "Flour, Sugar, Butter, Eggs, Chocolate Chips",
                            IsActive = true,
                            IsHome = true,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Chocolate Chip Cookie",
                            Price = 120m,
                            ShelfLife = "5 days",
                            StockQuantity = 50
                        },
                        new
                        {
                            Id = 8,
                            Allergens = "Eggs, Nuts",
                            CategoryId = 2,
                            CreatedDate = new DateTime(2024, 8, 5, 11, 27, 1, 867, DateTimeKind.Local).AddTicks(4875),
                            Description = "A delicate French pastry with a creamy filling.",
                            ImageUrl = "macaron.jpg",
                            Ingredients = "Almond Flour, Sugar, Egg Whites, Food Coloring",
                            IsActive = true,
                            IsHome = false,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Macaron",
                            Price = 150m,
                            ShelfLife = "1 week",
                            StockQuantity = 45
                        },
                        new
                        {
                            Id = 9,
                            Allergens = "Milk, Gluten",
                            CategoryId = 1,
                            CreatedDate = new DateTime(2024, 8, 6, 11, 27, 1, 867, DateTimeKind.Local).AddTicks(4878),
                            Description = "A buttery, flaky pastry.",
                            ImageUrl = "croissant.jpg",
                            Ingredients = "Flour, Butter, Sugar, Yeast, Salt",
                            IsActive = true,
                            IsHome = true,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Croissant",
                            Price = 125m,
                            ShelfLife = "2 days",
                            StockQuantity = 30
                        },
                        new
                        {
                            Id = 10,
                            Allergens = "Eggs, Milk, Gluten",
                            CategoryId = 2,
                            CreatedDate = new DateTime(2024, 8, 7, 11, 27, 1, 867, DateTimeKind.Local).AddTicks(4880),
                            Description = "A spiced pumpkin pie with a flaky crust.",
                            ImageUrl = "pumpkin-pie.jpg",
                            Ingredients = "Pumpkin, Sugar, Eggs, Cream, Spices, Flour",
                            IsActive = true,
                            IsHome = false,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Pumpkin Pie",
                            Price = 140m,
                            ShelfLife = "3 days",
                            StockQuantity = 20
                        },
                        new
                        {
                            Id = 11,
                            Allergens = "Eggs, Milk, Gluten",
                            CategoryId = 3,
                            CreatedDate = new DateTime(2024, 7, 27, 11, 27, 1, 867, DateTimeKind.Local).AddTicks(4882),
                            Description = "A classic red velvet cake with cream cheese frosting.",
                            ImageUrl = "red-velvet-cake.jpg",
                            Ingredients = "Flour, Sugar, Cocoa, Buttermilk, Eggs, Red Food Coloring",
                            IsActive = true,
                            IsHome = true,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Red Velvet Cake",
                            Price = 135m,
                            ShelfLife = "3 days",
                            StockQuantity = 30
                        },
                        new
                        {
                            Id = 12,
                            Allergens = "Eggs, Milk, Gluten",
                            CategoryId = 2,
                            CreatedDate = new DateTime(2024, 7, 28, 11, 27, 1, 867, DateTimeKind.Local).AddTicks(4884),
                            Description = "A moist bread made with ripe bananas.",
                            ImageUrl = "banana-bread.jpg",
                            Ingredients = "Flour, Sugar, Bananas, Eggs, Butter",
                            IsActive = true,
                            IsHome = false,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Banana Bread",
                            Price = 130m,
                            ShelfLife = "1 week",
                            StockQuantity = 25
                        },
                        new
                        {
                            Id = 13,
                            Allergens = "Milk, Gluten",
                            CategoryId = 3,
                            CreatedDate = new DateTime(2024, 7, 29, 11, 27, 1, 867, DateTimeKind.Local).AddTicks(4886),
                            Description = "A classic pie filled with spiced apples.",
                            ImageUrl = "apple-pie.jpg",
                            Ingredients = "Apples, Sugar, Flour, Butter, Cinnamon",
                            IsActive = true,
                            IsHome = true,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Apple Pie",
                            Price = 145m,
                            ShelfLife = "3 days",
                            StockQuantity = 20
                        },
                        new
                        {
                            Id = 14,
                            Allergens = "Eggs, Milk, Gluten",
                            CategoryId = 1,
                            CreatedDate = new DateTime(2024, 7, 30, 11, 27, 1, 867, DateTimeKind.Local).AddTicks(4889),
                            Description = "A choux pastry filled with cream and topped with chocolate.",
                            ImageUrl = "chocolate-eclair.jpg",
                            Ingredients = "Flour, Eggs, Butter, Cream, Chocolate",
                            IsActive = true,
                            IsHome = false,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Chocolate Eclair",
                            Price = 125m,
                            ShelfLife = "2 days",
                            StockQuantity = 15
                        });
                });

            modelBuilder.Entity("CoffeePattisserie.Entity.Concrete.PattisserieCategory", b =>
                {
                    b.Property<int>("PattisserieId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PattisserieId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("PattisserieCategories", (string)null);

                    b.HasData(
                        new
                        {
                            PattisserieId = 1,
                            CategoryId = 1
                        },
                        new
                        {
                            PattisserieId = 1,
                            CategoryId = 3
                        },
                        new
                        {
                            PattisserieId = 2,
                            CategoryId = 2
                        },
                        new
                        {
                            PattisserieId = 3,
                            CategoryId = 1
                        },
                        new
                        {
                            PattisserieId = 4,
                            CategoryId = 4
                        },
                        new
                        {
                            PattisserieId = 5,
                            CategoryId = 2
                        },
                        new
                        {
                            PattisserieId = 5,
                            CategoryId = 5
                        },
                        new
                        {
                            PattisserieId = 2,
                            CategoryId = 4
                        },
                        new
                        {
                            PattisserieId = 3,
                            CategoryId = 2
                        },
                        new
                        {
                            PattisserieId = 4,
                            CategoryId = 3
                        });
                });

            modelBuilder.Entity("CoffeePattisserie.Entity.Concrete.CoffeeCategory", b =>
                {
                    b.HasOne("CoffeePattisserie.Entity.Concrete.Category", "Category")
                        .WithMany("CoffeeCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoffeePattisserie.Entity.Concrete.Coffee", "Coffee")
                        .WithMany("CoffeeCategories")
                        .HasForeignKey("CoffeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Coffee");
                });

            modelBuilder.Entity("CoffeePattisserie.Entity.Concrete.MoctailCategory", b =>
                {
                    b.HasOne("CoffeePattisserie.Entity.Concrete.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoffeePattisserie.Entity.Concrete.Moctail", "Moctail")
                        .WithMany("MoctailCategories")
                        .HasForeignKey("MoctailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Moctail");
                });

            modelBuilder.Entity("CoffeePattisserie.Entity.Concrete.PattisserieCategory", b =>
                {
                    b.HasOne("CoffeePattisserie.Entity.Concrete.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoffeePattisserie.Entity.Concrete.Pattisserie", "Pattisserie")
                        .WithMany("PattisserieCategories")
                        .HasForeignKey("PattisserieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Pattisserie");
                });

            modelBuilder.Entity("CoffeePattisserie.Entity.Concrete.Category", b =>
                {
                    b.Navigation("CoffeeCategories");
                });

            modelBuilder.Entity("CoffeePattisserie.Entity.Concrete.Coffee", b =>
                {
                    b.Navigation("CoffeeCategories");
                });

            modelBuilder.Entity("CoffeePattisserie.Entity.Concrete.Moctail", b =>
                {
                    b.Navigation("MoctailCategories");
                });

            modelBuilder.Entity("CoffeePattisserie.Entity.Concrete.Pattisserie", b =>
                {
                    b.Navigation("PattisserieCategories");
                });
#pragma warning restore 612, 618
        }
    }
}
